version: '3.8'

networks:
  whaticket:

services:
  mysql:
    image: mariadb:10.6
    container_name: whaticket-mysql
    restart: always
    environment:
      MYSQL_DATABASE: whaticket
      MYSQL_ROOT_PASSWORD: p@P7bZ#Aq!M9uE2vXs3KjL6*b
      TZ: America/Fortaleza
    volumes:
      - ./.docker/data/:/var/lib/mysql
    networks:
      - whaticket

  backend:
    build:
      context: ./backend
    container_name: whaticket-backend
    environment:
      DB_HOST: whaticket-mysql
      DB_USER: root
      DB_PASS: p@P7bZ#Aq!M9uE2vXs3KjL6*b
      DB_NAME: whaticket
      JWT_SECRET: 7373cf63bf6d3fdb4fad5453c5f04b72921643d91e53fda0b5c81c0faf5b3b9c
      JWT_REFRESH_SECRET: 3e132995785512d4fdb9d034a1c0488e0d7134503286817310789e1cb02ac08d
      BACKEND_URL: https://api.whatsapp.helprecurso.com.br
      FRONTEND_URL: https://whatsapp.helprecurso.com.br
      CHROME_ARGS: --no-sandbox --disable-setuid-sandbox
    volumes:
      - ./backend/public:/usr/src/app/public
      - ./backend/.wwebjs_auth:/usr/src/app/.wwebjs_auth
    networks:
      - whaticket
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whaticket-backend.rule=Host(`api.whatsapp.helprecurso.com.br`)"
      - "traefik.http.services.whaticket-backend.loadbalancer.server.port=3000"

  frontend:
    build:
      context: ./frontend
    container_name: whaticket-frontend
    environment:
      REACT_APP_BACKEND_URL: https://api.whatsapp.helprecurso.com.br/
    networks:
      - whaticket
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whaticket-frontend.rule=Host(`whatsapp.helprecurso.com.br`)"
      - "traefik.http.services.whaticket-frontend.loadbalancer.server.port=80"
