version: '3.8'

networks:
  whaticket:

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: whaticket-backend
    environment:
      DB_HOST: whaticket-whaticketdb-5n9hyq
      DB_USER: root
      DB_PASS: p@P7bZ#Aq!M9uE2vXs3KjL6^b
      DB_NAME: whaticket
      JWT_SECRET: 7373cf63bf6d3fdb4fad5453c5f04b72921643d91e53fda0b5c81c0faf5b3b9c
      JWT_REFRESH_SECRET: 3e132995785512d4fdb9d034a1c0488e0d7134503286817310789e1cb02ac08d
      BACKEND_URL: https://api.whatsapp.helprecurso.com.br
      FRONTEND_URL: https://whatsapp.helprecurso.com.br
      CHROME_ARGS: --no-sandbox --disable-setuid-sandbox
      NODE_ENV: production
    volumes:
      - ./backend/public:/usr/src/app/public
      - ./backend/.wwebjs_auth:/usr/src/app/.wwebjs_auth
    networks:
      - whaticket
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whaticket-backend.rule=Host(`api.whatsapp.helprecurso.com.br`)"
      - "traefik.http.routers.whaticket-backend.entrypoints=websecure"
      - "traefik.http.routers.whaticket-backend.tls=true"
      - "traefik.http.services.whaticket-backend.loadbalancer.server.port=3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: whaticket-frontend
    environment:
      REACT_APP_BACKEND_URL: https://api.whatsapp.helprecurso.com.br/
      NODE_ENV: production
    depends_on:
      - backend
    networks:
      - whaticket
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whaticket-frontend.rule=Host(`whatsapp.helprecurso.com.br`)"
      - "traefik.http.routers.whaticket-frontend.entrypoints=websecure"
      - "traefik.http.routers.whaticket-frontend.tls=true"
      - "traefik.http.services.whaticket-frontend.loadbalancer.server.port=80"
